server:
  port: 8085

spring:
  application:
    name: CONFIGURATION SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Abhikanade17112002/Configuration-Server
          clone-on-startup: true

